logic to move files into root dir (#62)
BrettMayson/Arma3Server pull request #63
Opened 2023-04-29 17:03 UTC by Inmaan

add logic to move files into server root directory

2023-04-29 20:53 UTC, BrettMayson commented
What are you needing this functionality for?

2023-05-01 21:54 UTC, Inmaan commented
For the mod [Exile](http://www.exilemod.com), as part of the server side installation setup there is a dll file that need to be in the root directory of the server.

2023-05-12 00:53 UTC, arh78750 requested changes

2023-05-12 00:53 UTC, arh78750 commented on launch.py
> +from pathlib import Path
the linter wants you to move this down to the other `from import` statement

2023-05-12 00:53 UTC, arh78750 commented on launch.py
> +            shutil.copy2(BASE_DIR / "move_to_root" / file, BASE_DIR / file)
Linter wants 
/github/workspace/launch.py:48:53: E225 missing whitespace around operator
/github/workspace/launch.py:52:76: W291 trailing whitespace
```suggestion
            shutil.copy2(BASE_DIR / "move_to_root" / file, BASE_DIR / file)
```

2023-05-12 00:53 UTC, arh78750 commented on launch.py
> +        if os.path.isdir(BASE_DIR / "move_to_root" /file):
```suggestion
        if os.path.isdir(BASE_DIR / "move_to_root" / file):
```

2023-06-17 13:48 UTC, Inmaan commented on launch.py
> -    steamcmd.extend(["+login", os.environ["STEAM_USER"], os.environ["STEAM_PASSWORD"]])
flake8, line was too long

2026-08-24 07:55 UTC, closed without merging